---
- name: running load balancer server
  command: /opt/jboss-eap-7.0/bin/standalone.sh -Djboss.server.base.dir=/opt/lb -Djboss.bind.address={{ master_ip }} -Djboss.socket.binding.port-offset=1000 -c standalone-ha.xml
